name: Build linux binary

on: [push]

# Based on https://www.swift.org/server/guides/deploying/ubuntu.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build inside docker
        run: |
          docker run --rm \
            -v "$PWD:/workspace" \
            -w /workspace \
            --platform linux/amd64 \
            swift:5.8  \
            /bin/bash -cl '\
            swift --version &&\
            ./scripts/build_release.sh'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            .build/install
