name: Build linux binary

on:
  push:
    branches:
      - main

# Based on https://www.swift.org/server/guides/deploying/ubuntu.html
jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build inside docker
        run: |
          docker run --rm \
            -v "$PWD:/workspace" \
            -w /workspace \
            --platform linux/amd64 \
            swift:5.8.0-bionic  \
            /bin/bash -cl '\
            swift --version &&\
            ./scripts/build_release_in_linux.sh'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ManifoldTradingBot-release
          path: |
            CLI_build
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ManifoldTradingBot-release
          path: release-artifact
      - run: find -maxdepth 2 -ls
      - name: Copy artifact via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: release-artifact/*
          target: ManifoldTradingBot
      - name: Move artifact output to correct folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            mv ManifoldTradingBot ManifoldTradingBot.bak
            mv ManifoldTradingBot.bak/ManifoldTradingBot-release ManifoldTradingBot
      - name: Copy service
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "scripts/server/manifold-trading-bot.service"
          target: /etc/systemd/system
      - name: Restart service using the new binary
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart manifold-trading-bot
            sudo systemctl enable manifold-trading-bot
