name: Build and deploy linux binary

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: go/go.sum

      - name: Install dependencies + Build
        run: |
             cd go
             go get .
             CGO_ENABLED=0 go build -o manifoldtradingbot
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ManifoldTradingBot-release
          path: |
            go/manifoldtradingbot
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ManifoldTradingBot-release
          path: release-artifact
      - name: Copy artifact via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "release-artifact/"
          target: ManifoldTradingBot
      - name: Copy service
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "go/scripts/server/manifold-trading-bot.service"
          target: temp_folder
      - name: Finishing up
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            # Move new binary to correct folder, save old as .bak
            rm -rf ManifoldTradingBot.bak
            mv ManifoldTradingBot ManifoldTradingBot.bak
            mv ManifoldTradingBot.bak/release-artifact ManifoldTradingBot
            chmod 777 ManifoldTradingBot/manifoldtradingbot

            # Restart service
            sudo mv temp_folder/go/scripts/server/manifold-trading-bot.service /etc/systemd/system/manifold-trading-bot.service
            rm -rf temp_folder
            sudo systemctl daemon-reload
            sudo systemctl restart manifold-trading-bot
            sudo systemctl enable manifold-trading-bot
