name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test --allow-all

      - name: Build Linux executable
        run: deno compile --allow-env --allow-write --allow-read --allow-net --target x86_64-unknown-linux-gnu --output dist/ManifoldTradingBot src/main.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ManifoldTradingBot-linux
          path: dist/ManifoldTradingBot

      - name: Deploy to server
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_USERNAME: ${{ secrets.DEPLOY_SSH_USERNAME }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "sudo systemctl stop manifold-trading-bot"
          scp -i deploy_key -o StrictHostKeyChecking=no dist/ManifoldTradingBot $SSH_USERNAME@$SSH_HOST:/home/manifoldtradingbot/ManifoldTradingBot
          ssh -i deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "sudo systemctl start manifold-trading-bot"
          rm deploy_key
