name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test --allow-all

      - name: Build Linux executable
        run: deno compile --allow-read --allow-net --target x86_64-unknown-linux-gnu --output dist/ManifoldTradingBot src/main.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ManifoldTradingBot-linux
          path: dist/ManifoldTradingBot
