name: Test CLI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test inside docker
        run: |
          docker run --rm \
            -v "$PWD/swift:/workspace" \
            -w /workspace \
            --platform linux/amd64 \
            swift:5.8  \
            /bin/bash -cl '\
            swift --version &&\
            ./scripts/test_in_linux.sh'
